pipeline {
    agent {
        node { label "master" }
    }
    stages {
        stage('Prepare Git Code') {
            steps {
                echo "Prepare Git Code"
                sh "ls"
                sh "ls;cd hello-kubernetes/app;ls"
 
                echo 'Preparing end..'
            }
        }
        stage("Build") {
            steps {
                echo 'Build end..'
                sh "cd hello-kubernetes/app;docker build . -t localhost:5000/littleserver:dev"
            }
        }
        stage("Get Dockerfile & Bootstart.sh") {
          steps {
            echo 'Get Dockerfile end..'
            }
        }
        stage("DockerBuild") {
          steps {
                echo 'DockerBuild end..'}
        }
        stage("DockerPush") {
          steps {
                
                echo 'DockerPush end..'
                }
 
        }
        
        stage("Deploy") {
          steps {
                sh "docker run -d -p 8001:8080 localhost:5000/littleserver:dev"
                echo 'DockerDeploy end..'
                }
 
        }
    }
}
