pipeline {
    agent {
        node { label "master" }
    }
    stages {
        stage('Prepare Git Code') {
            steps {
                echo "Prepare Git Code"
                ls
                cd hello-kubernetes\app
 
                echo 'Preparing end..'
            }
        }
        stage("Build") {
            steps {
                echo 'Build end..'
                cd hello-kubernetes\app
                docker build . -t localhost:5000/littleserver:1
            }
        }
        stage("Get Dockerfile & Bootstart.sh") {
          steps {
            echo 'Get Dockerfile end..'
            }
        }
        stage("DockerBuild") {
          steps {
                echo 'DockerBuild end..'}
        }
        stage("DockerPush") {
          steps {
           
                echo 'DockerPush end..'
                }
 
        }
    }
}