apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: flask
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30008
  selector:
    app: my-python-app
    type: backend